name: Deploy

on:
  push:
    branches: [ main ] # run whenever you push to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Inject personal.json (raw)
        shell: bash
        run: |
          mkdir -p public
          # write exactly what's in the secret
          printf '%s' "$PERSONAL_JSON" > public/personal.json
          echo "Bytes:" $(wc -c < public/personal.json)
          head -n 1 public/personal.json || true
        env:
          PERSONAL_JSON: ${{ secrets.PERSONAL_JSON }}

      - run: npm ci
      - run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist